repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        require_serial: true
        language: system
        types: [python]
      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check
        require_serial: true
        language: system
        types: [python]
      - id: ty
        name: ty
        entry: uv run ty check
        require_serial: true
        language: system
        types: [python]
